### PR TITLE
Hide color picker on save

### PR DESCRIPTION
**Pull request by marcmascarell**

### CODE REVIEW

**Comment by lacymorrow** [comment]
Is the color picker not hiding on save for you?

What system are you using?

I'm merging but this _should_be redundant code :)

**Comment by marcmascarell** [comment]
On Linux. In fact, drag and app menu does not work on Linux (Elementary OS).

**Comment by lacymorrow** [comment]
Okay thanks, I'm going to pull this out for now and test again on elementary.

If you have a minute, could you try the latest release?

**Comment by lacymorrow** [comment]
Thanks for testing it out for me, I assumed incorrectly that Chromium would be stable across platforms. I'll make some changes today.

**Comment by lacymorrow** [comment]
Do you mean the Crosshair select, or the OS application menu?

**Comment by lacymorrow** [comment]
I see what you mean on elementaryOS:
- Unable to drag (`CTRL`+`SHIFT`+Arrows works)
- Unable to hide the settings and rest of the application
- Toggle lock seems to make the crosshair opacity 100%
- Resizing the crosshair a bunch leaves behind artifacts in the settings window:
Screen Shot 2019-10-10 at 11 03 56 AM

**Comment by lacymorrow** [comment]
Tracking issues: https://github.com/lacymorrow/crossover/issues/5

**Pull request merged**
